#!/usr/bin/env bash
# a lot of extra traps
file=/var/run/holbertonscript.pid
function finishQuit {
    sudo rm $file
    exit
}
function finishTerm {
    echo 'I hate the kill command'
    sudo rm $file
    exit
}
trap finishTerm SIGTERM
trap finishQuit SIGQUIT
trap "echo 'Y U no love me?!'" SIGINT
sudo bash -c "echo $$ > $file"
while ((1))
do
    echo "To infinity and beyond"
    sleep 2
done
