#!/usr/bin/env bash
#manages the manage_process
file=/var/run/my_process.pid
if [ "$1" == "start" ];
then
    ./manage_my_process &
    sudo bash -c "echo $! > $file"
    echo "manage_my_process started"
elif [ "$1" == "stop" ];
then
    pkill -f ./manage_my_process
    sudo rm $file
    echo "manage_my_process stopped"
elif [ "$1" == "restart" ];
then
    pkill -f ./manage_my_process
    sudo rm $file
    ./manage_my_process &
    sudo bash -c "echo $! > $file"
    echo "manage_my_process restarted"
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
