#!/usr/bin/env bash
#while case stuff

count=1
while [ $count -ne 21 ]
do
    echo $count
    case "$count" in
	4)  echo "bad luck from China"
	    ;;
	9) echo "bad luck from Japan"
	    ;;
	17) echo "bad luck from Italy"
	    ;;
	esac
    ((count++))
done
